name: Feature Request
description: Request a new feature
labels: ["feature_request"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What feature should we add?
      description: Include any relevant examples or reference material
    validations:
      required: true
  - type: textarea
    id: cute-animal
    attributes:
      label: Cute animal photo
      description: Paste a picture of a cute animal in the box below
      value: "![Put a link to a cute animal picture inside the parenthesis-->]()"
    validations:
      required: false
